### ISSUE TITLE
Missing deployment folder

### ISSUE THREAD

**Issue by digitalron** [ExpediaDotCom/haystack-collector#56]
There seems to be a missing deployment/terraform folder?

<img width="1001" alt="screen shot 2018-11-05 at 12 14 21" src="https://user-images.githubusercontent.com/2234684/47995071-7850bf80-e0f4-11e8-91eb-ba22d5d53ccb.png">

https://github.com/ExpediaDotCom/haystack/blob/2b18c96febf86976abfa2a29060329032abc8469/deployment/terraform/modules/haystack-apps/kubernetes/main.tf#L54

Getting this:

`- module.haystack-apps.collectors
  Getting source "github.com/ExpediaDotCom/haystack-collector/deployment/terraform"
Error downloading modules: Error loading modules: subdir "deployment/terraform" not found`

**Comment by ashishagg** [comment]
This has been fixed. I am closing this issue.
Thanks for reporting it.
